url: https://rawajitqan.github.io
baseurl: https://rawajitqan.github.io

# Site settings
title: RAWAJ ALITQAN
email: pmo@rawajitqan.com
description: "Rawaj Al-Itqan was established in 2012. The establishment has grown steadily with frequently success for the completion of various projects, so that it formed a stable financial base and staff with highly experienced and knowledgeable with the strict requirements for different projects, where the team acquired many years of experience participation in large-scale projects."


# Team names, titles and social links


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rawajalitqan
  - title: facebook
    url: https://www.facebook.com/RAWAJ-Aitqan-Est-264712217481264
  - title: instagram
    url: https://www.instagram.com/rawajalitqan/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
